import * as React from "react";
import { cn } from "@/lib/utils";
import { cva } from "class-variance-authority";
const useFormField = React.forwardRef((props, ref) => { const { className, children, ...rest } = props; return <div ref={ref} className={cn(className)} {...rest}>{children}</div>; }); useFormField.displayName="useFormField";
const Form = React.forwardRef((props, ref) => { const { className, children, ...rest } = props; return <div ref={ref} className={cn(className)} {...rest}>{children}</div>; }); Form.displayName="Form";
const FormItem = React.forwardRef((props, ref) => { const { className, children, ...rest } = props; return <div ref={ref} className={cn(className)} {...rest}>{children}</div>; }); FormItem.displayName="FormItem";
const FormLabel = React.forwardRef((props, ref) => { const { className, children, ...rest } = props; return <div ref={ref} className={cn(className)} {...rest}>{children}</div>; }); FormLabel.displayName="FormLabel";
const FormControl = React.forwardRef((props, ref) => { const { className, children, ...rest } = props; return <div ref={ref} className={cn(className)} {...rest}>{children}</div>; }); FormControl.displayName="FormControl";
const FormDescription = React.forwardRef((props, ref) => { const { className, children, ...rest } = props; return <div ref={ref} className={cn(className)} {...rest}>{children}</div>; }); FormDescription.displayName="FormDescription";
const FormMessage = React.forwardRef((props, ref) => { const { className, children, ...rest } = props; return <div ref={ref} className={cn(className)} {...rest}>{children}</div>; }); FormMessage.displayName="FormMessage";
const FormField = React.forwardRef((props, ref) => { const { className, children, ...rest } = props; return <div ref={ref} className={cn(className)} {...rest}>{children}</div>; }); FormField.displayName="FormField";
export { useFormField, Form, FormItem, FormLabel, FormControl, FormDescription, FormMessage, FormField };