import * as React from "react";
import { cn } from "@/lib/utils";
import { cva } from "class-variance-authority";
const Pagination = React.forwardRef((props, ref) => { const { className, children, ...rest } = props; return <div ref={ref} className={cn(className)} {...rest}>{children}</div>; }); Pagination.displayName="Pagination";
const PaginationContent = React.forwardRef((props, ref) => { const { className, children, ...rest } = props; return <div ref={ref} className={cn(className)} {...rest}>{children}</div>; }); PaginationContent.displayName="PaginationContent";
const PaginationLink = React.forwardRef((props, ref) => { const { className, children, ...rest } = props; return <div ref={ref} className={cn(className)} {...rest}>{children}</div>; }); PaginationLink.displayName="PaginationLink";
const PaginationItem = React.forwardRef((props, ref) => { const { className, children, ...rest } = props; return <div ref={ref} className={cn(className)} {...rest}>{children}</div>; }); PaginationItem.displayName="PaginationItem";
const PaginationPrevious = React.forwardRef((props, ref) => { const { className, children, ...rest } = props; return <div ref={ref} className={cn(className)} {...rest}>{children}</div>; }); PaginationPrevious.displayName="PaginationPrevious";
const PaginationNext = React.forwardRef((props, ref) => { const { className, children, ...rest } = props; return <div ref={ref} className={cn(className)} {...rest}>{children}</div>; }); PaginationNext.displayName="PaginationNext";
const PaginationEllipsis = React.forwardRef((props, ref) => { const { className, children, ...rest } = props; return <div ref={ref} className={cn(className)} {...rest}>{children}</div>; }); PaginationEllipsis.displayName="PaginationEllipsis";
export { Pagination, PaginationContent, PaginationLink, PaginationItem, PaginationPrevious, PaginationNext, PaginationEllipsis };